#!/usr/bin/env bash

set -u

declare -rx URL=$1
declare -rx BIN=".bin"
declare -rx CONFIGURATION="--config-location 'download.conf'"
declare -rx USERNAME="--username USERNAME"
declare -rx PASSWORD="--username USERNAME"
declare -rx AUTHENTICATION="${USERNAME} ${PASSWORD}"


echo Bin $BIN
echo URL $1
echo CONFIGURATION $CONFIGURATION
echo OPIONS $OPTIONS

source $BIN/.arguments


echo Downloading from YouTube ➡️  $1
# youtube-dl \
#   $OPTIONS \
#$URL
