#!/usr/bin/env bash

set -u

declare -rx URL=$1
declare -rx BIN=".bin"
declare -rx CONFIGURATION="--config-location 'download.conf'"
declare -rx USERNAME="--username USERNAME"
declare -rx PASSWORD="--username USERNAME"
declare -rx AUTHENTICATION="${USERNAME} ${PASSWORD}"


echo Bin $BIN
echo URL $URL
echo CONFIGURATION $CONFIGURATION

source $BIN/.arguments


echo
echo Downloading from YouTube ➡️  $1
echo

youtube-dl \
  --simulate \
  --get-id \
  --get-title \
  --get-description \
  --get-filename \
  --get-thumbnail \
  --get-duration \
  --get-format \
  --get-url \
$URL

# --get-url \
# --list-subs \
# --list-formats \
